### PR TITLE
I needed to delete options for server to resolve mongo error

### PR DESCRIPTION
**Pull request by thinklikeadesigner**
### Changed this

Screen Shot 2021-10-30 at 5 50 16 PM

### to this

Screen Shot 2021-10-30 at 5 50 44 PM

### CODE REVIEW

**Comment by vgalilei** [comment]
@thinklikeadesigner can you please explain what issue would you like to solve?

**Comment by thinklikeadesigner** [comment]
I don't understand, but I talked to jake and he said the options were unnecessary. I will look up what they do, i just know that including them broke the server.

I will post the error message

**Comment by thinklikeadesigner** [comment]
this was the issue I fixed in api/investor PR. I wanted to move it to its own hotfix branch

**Comment by thinklikeadesigner** [comment]
@vgalilei I removed this fix from the other PRs so we can merge this one if that's okay

**Review by vgalilei — APPROVED** [review]
LGTM

**Comment by thinklikeadesigner** [comment]
### This change was made to fix this error

```bash
~/Desktop/projects/venturecat/venturecat/backend main ❯ npm run dev

> backend@1.0.0 dev
> nodemon app.js

[nodemon] 2.0.14
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
/Users/everest/Desktop/projects/venturecat/venturecat/backend/node_modules/mongodb/lib/connection_string.js:291
        throw new error_1.MongoParseError(`${optionWord} ${Array.from(unsupportedOptions).join(', ')} ${isOrAre} not supported`);
              ^

MongoParseError: options usecreateindex, usefindandmodify are not supported
    at Object.parseOptions (/Users/everest/Desktop/projects/venturecat/venturecat/backend/node_modules/mongodb/lib/connection_string.js:291:15)
    at new MongoClient (/Users/everest/Desktop/projects/venturecat/venturecat/backend/node_modules/mongodb/lib/mongo_client.js:62:46)
    at /Users/everest/Desktop/projects/venturecat/venturecat/backend/node_modules/mongoose/lib/connection.js:779:16
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (/Users/everest/Desktop/projects/venturecat/venturecat/backend/node_modules/mongoose/lib/connection.js:776:19)
    at /Users/everest/Desktop/projects/venturecat/venturecat/backend/node_modules/mongoose/lib/index.js:330:10
    at /Users/everest/Desktop/projects/venturecat/venturecat/backend/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/Users/everest/Desktop/projects/venturecat/venturecat/backend/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/Users/everest/Desktop/projects/venturecat/venturecat/backend/node_modules/mongoose/lib/index.js:1151:10)
[nodemon] app crashed - waiting for file changes before starting...
```

**Pull request merged**
