### PR TITLE
Static response for GET /api/investor

### PR DESCRIPTION
**Pull request by thinklikeadesigner**
### [Trello card Static response for GET /api/investor] (https://trello.com/c/d4kPSSOr)

static response for  ```GET api/investor```

### CODE REVIEW

**Comment by thinklikeadesigner** [comment]
made changes by adding server, and route for investor

**Comment by thinklikeadesigner** [comment]
### I added an ```index.js``` folder in ```backend/routes```
I think this will be a useful place to collect all routes in one place

Screen Shot 2021-10-30 at 3 49 03 PM

**Comment by vgalilei** [comment]
Yeah, it is exaclty what i was thinking!

**Comment by vgalilei** [comment]
Could you please resolve conflicts? Also it will be good to have only one change per PR

**Comment by thinklikeadesigner** [comment]
Yes, i think I fixed the mongoose.connect and that should have been in a hotfix, sorry!

**Comment by thinklikeadesigner** [comment]
Okay I cleaned up this PR to only include server changes @vgalilei

**Review by vgalilei — APPROVED** [review]
LGTM

**Pull request merged**
